### ISSUE TITLE
How many days does the pretraining take?

### ISSUE THREAD

**Issue by zhouweii234** [sallymmx/TransVOS#1]
Is 1.5 days the total time of the two stages of training?

**Comment by Jieqianyu** [comment]
The main training takes about 1.5 days.

**Comment by lzl2040** [comment]
> The main training takes about 1.5 days.

What about pretraining?How many epoches does it train?

**Comment by Jieqianyu** [comment]
It takes about 10 epochs for pretrain.-------- 原始邮件 --------发件人： lzl2040 ***@***.***>日期： 2022年11月14日周一 15:55收件人： sallymmx/TransVOS ***@***.***>抄送： JM ***@***.***>, State change ***@***.***>主    题： Re: [sallymmx/TransVOS] How many days does the pretraining take? (#1)

The main training takes about 1.5 days.

What about pretraining?How many epoches does it train?

**Comment by lzl2040** [comment]
> It takes about 10 epochs for pretrain.-------- 原始邮件 --------发件人： lzl2040 ***@***.***>日期： 2022年11月14日周一 15:55收件人： sallymmx/TransVOS ***@***.***>抄送： JM ***@***.***>, State change ***@***.***>主 题： Re: [sallymmx/TransVOS] How many days does the pretraining take? (#1) The main training takes about 1.5 days. What about pretraining?How many epoches does it train? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Thank you for your reply!And the config about the pretraing is the same as the main training except the epoches?
