### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by fishtoo** [sallymmx/TransVOS#2]
Hi, we follow your default config and train on V100 with 32GB. However, it raise out of memory error. We have to reduce the batch size from 4 to 1 in order to fit in the gpu memory. I wonder if there is any mismatch between the code in the repo and the one you used to train on TITAN RTX which has 24GB gpu memory? Thanks

**Comment by Jieqianyu** [comment]
We use 4 TITAN RTX GPUs with batchsize 4 to train the model. Actually, the batchsize of each gpu is 1.

**Comment by fishtoo** [comment]
Thanks for the reply. So the batch size in the config means the total number of videos across all the gpus? Also, do you use the same config for the pretrain (train for 160 epochs)?

**Comment by Jieqianyu** [comment]
(1) Yes; (2) Models were pretrained for 12 epochs with scheduler-step 10. And the input resolution was reduced to 240x427.

**Comment by lzl2040** [comment]
> (1) Yes; (2) Models were pretrained for 12 epochs with scheduler-step 10. And the input resolution was reduced to 240x427.

请问预训练时的config跟在真实视频上的训练的config有什么不同吗
